### ISSUE TITLE
feature: generator

### ISSUE THREAD

**Issue by zrp9** [ZacP-stack/PwdManager#7]
users want to generate passwords

**Comment by Oddish1** [comment]
completed on my dev branch, will need to be merged to main

**Comment by Oddish1** [comment]
Need to implement toast to display errors for:
1. Password length too short to match the other criteria
2. Password length longer than criteria.
For the second case: for now I have it set to automatically add extra letters to fill out the extra length. We can keep it like that, I haven't figured out how to auto-increment the forms to equal the total length.
